version: '3.8'
services:
  dev-db:
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres,
      POSTGRES_PASSWORD: postgres,
      POSTGRES_DB: dbTest
    networks:
      - dev-tedy
networks:
  dev-tedy:
